modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/GoryMoon/InfoDataPack"
[[mods]]
    modId="infodatapack"
    version="${file.jarVersion}"
    displayName="Info DataPack"
    credits="Thanks to Darkosto for the idea"
    authors="GoryMoon"
    description='''
A mod that allows you add custom tooltips to items through datapacks.
You can also add JEI information pages to items
'''

[[dependencies.infodatapack]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infodatapack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infodatapack]]
    modId="jei"
    mandatory=false
    versionRange="[7.6.0.52,)"
    ordering="BEFORE"
    side="CLIENT"
