modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/GoryMoon/InfoDataPack"
[[mods]]
    modId="infodatapack"
    version="${file.jarVersion}"
    displayName="Info DataPack"
    itemIcon="minecraft:paper"
    credits="Thanks to Darkosto for the idea"
    authors="GoryMoon"
    description='''
A mod that allows you add custom tooltips to items through datapacks.
You can also add JEI information pages to items
'''

[[dependencies.infodatapack]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infodatapack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infodatapack]]
    modId="jei"
    mandatory=false
    versionRange="[9.3.0.86,)"
    ordering="BEFORE"
    side="CLIENT"
