modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/GoryMoon/InfoDataPack"
[[mods]]
    modId="infodatapack"
    version="${file.jarVersion}"
    displayName="Info DataPack"
    itemIcon="minecraft:paper"
    credits="Thanks to Darkosto for the idea"
    authors="GoryMoon"
    description='''
A mod that allows you add custom tooltips to items through datapacks.
You can also add JEI information pages to items
'''

[[dependencies.infodatapack]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infodatapack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infodatapack]]
    modId="jei"
    mandatory=false
    versionRange="[11.2.0,)"
    ordering="BEFORE"
    side="CLIENT"
